name: Daily AI Advice

on:
  schedule:
    # This will run the job every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  generate-advice:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements.txt file
        # If you don't have a requirements.txt, you can install packages directly:
        # pip install package1 package2

    - name: Run get_ai_advice.py
      run: python get_ai_advice.py

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update daily AI advice" && git push)
