name: Daily AI Advice

on:
  schedule:
  # This will run the job every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-advice:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # If you need specific packages, install them here:
        # pip install package1 package2

    - name: Run get_ai_advice.py
      run: python get_ai_advice.py

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update daily AI advice" && git push)
